### ISSUE TITLE
Slight issues when trying to download and install the CLI

### ISSUE THREAD

**Issue by holosam** [flightcrewhq/crewcli#8]
- [x] Was getting a `404` when running `https://raw.githubusercontent.com/flightcrewhq/crewcli/main/bootstrap.sh`. The script started to work when I added `?token=...` to the url, but then failed to download the checksums.txt, so I realized the repo just had to be open sourced for those without access
   - Side note I think this means my local git config has the wrong token if I wasn't able to access it out of the box? But that's a good thing in this case
- [x] I got `permission denied` on the move call, so I had to change it to `| sudo bash` to be able to run that command
- [x] Even with running `export OUTDIR=...`, it still put the binary in my working directory instead of the OUTDIR

This issue can more be posed as questions of "What did I do wrong?" rather than assuming something about the scripts need to be fixed.

**Comment by holosam** [comment]
Probably belongs in its own issue but it's late and I'm just kind of taking notes all in one place right now.

I tried to create the VM `flightcrew-control-tower-dev`, and the script said the VM exists already (which it doesn't). My guess is that since the VM `flightcrew-control-tower-dev-dev-03` exists already, we're checking a regex and need to add `^$`, or check for a space after the VM name if using `awk`.

**Comment by chrisyxlee** [comment]
From @JimTichols:

> 1. CLI was truncating the API token, we had to reduce the token to a shorter length
> 2. gcloud path (???) errors

@holosam explained that the `gcloud` path errors are because `gcloud` wasn't in the PATH env var.
